version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sa_user
      POSTGRES_PASSWORD: sa_pass
      POSTGRES_DB: sistema_academico
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
