"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _boleta from './boleta.bones.json'

configureBoneyard({"color":"#1e2230","darkColor":"#1e2230","animate":"shimmer","shimmerColor":"#262b3a","darkShimmerColor":"#262b3a","speed":"2s"})

registerBones({
  "boleta": _boleta,
})
