"""add_stripe_session_id_to_pagos_online

Revision ID: 61880be1d112
Revises: b42cc57fda33
Create Date: 2026-07-22 14:45:48.337153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61880be1d112'
down_revision: Union[str, Sequence[str], None] = 'b42cc57fda33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos_online', sa.Column('stripe_session_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos_online', 'stripe_session_id')
    # ### end Alembic commands ###
