"""add_created_at_to_solicitudes_equivalencia

Revision ID: a22743f21549
Revises: c0e2c42a4b9d
Create Date: 2026-07-22 15:32:22.607708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22743f21549'
down_revision: Union[str, Sequence[str], None] = 'c0e2c42a4b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_equivalencia', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitudes_equivalencia', 'created_at')
    # ### end Alembic commands ###
