"""feat: agregar ondelete cascada/setnull a FKs

Revision ID: b42cc57fda33
Revises: k7l8m9n0p1q2
Create Date: 2026-07-22 14:36:09.878334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b42cc57fda33'
down_revision: Union[str, Sequence[str], None] = 'k7l8m9n0p1q2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temarios_id'), table_name='temarios')
    op.drop_table('temarios')
    op.alter_column('apuntes', 'fecha_subida',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('apuntes_user_id_fkey'), 'apuntes', type_='foreignkey')
    op.create_foreign_key(None, 'apuntes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('becas_activas_otorgado_por_fkey'), 'becas_activas', type_='foreignkey')
    op.drop_constraint(op.f('becas_activas_beca_id_fkey'), 'becas_activas', type_='foreignkey')
    op.create_foreign_key(None, 'becas_activas', 'users', ['otorgado_por'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'becas_activas', 'becas_catalogo', ['beca_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('becas_catalogo_fuente_id_fkey'), 'becas_catalogo', type_='foreignkey')
    op.create_foreign_key(None, 'becas_catalogo', 'fuentes_beca', ['fuente_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comprobantes_pago_id_fkey'), 'comprobantes', type_='foreignkey')
    op.create_foreign_key(None, 'comprobantes', 'pagos', ['pago_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cuotas_generado_por_fkey'), 'cuotas', type_='foreignkey')
    op.drop_constraint(op.f('cuotas_concepto_id_fkey'), 'cuotas', type_='foreignkey')
    op.create_foreign_key(None, 'cuotas', 'users', ['generado_por'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cuotas', 'conceptos_arancel', ['concepto_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('equivalencias_materia_solicitud_id_fkey'), 'equivalencias_materia', type_='foreignkey')
    op.create_foreign_key(None, 'equivalencias_materia', 'solicitudes_equivalencia', ['solicitud_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('eventos_calendario_creado_por_fkey'), 'eventos_calendario', type_='foreignkey')
    op.create_foreign_key(None, 'eventos_calendario', 'users', ['creado_por'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('examenes_profesor_id_fkey'), 'examenes', type_='foreignkey')
    op.create_foreign_key(None, 'examenes', 'users', ['profesor_id'], ['id'], ondelete='SET NULL')
    op.alter_column('foro_hilos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('foro_mensajes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('informes_pasantia_pasantia_id_fkey'), 'informes_pasantia', type_='foreignkey')
    op.create_foreign_key(None, 'informes_pasantia', 'pasantias', ['pasantia_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('inscripciones_alumno_id_fkey'), 'inscripciones', type_='foreignkey')
    op.create_foreign_key(None, 'inscripciones', 'users', ['alumno_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('pagos_cuota_id_fkey'), 'pagos', type_='foreignkey')
    op.create_foreign_key(None, 'pagos', 'cuotas', ['cuota_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pasantias_tutor_academico_id_fkey'), 'pasantias', type_='foreignkey')
    op.drop_constraint(op.f('pasantias_empresa_id_fkey'), 'pasantias', type_='foreignkey')
    op.create_foreign_key(None, 'pasantias', 'empresas_receptoras', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pasantias', 'users', ['tutor_academico_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('postulaciones_beca_revisado_por_fkey'), 'postulaciones_beca', type_='foreignkey')
    op.drop_constraint(op.f('postulaciones_beca_beca_id_fkey'), 'postulaciones_beca', type_='foreignkey')
    op.create_foreign_key(None, 'postulaciones_beca', 'users', ['revisado_por'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'postulaciones_beca', 'becas_catalogo', ['beca_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('procesos_graduacion_tutor_id_fkey'), 'procesos_graduacion', type_='foreignkey')
    op.create_foreign_key(None, 'procesos_graduacion', 'users', ['tutor_id'], ['id'], ondelete='SET NULL')
    op.alter_column('recordatorios_docente', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('recordatorios_docente_profesor_id_fkey'), 'recordatorios_docente', type_='foreignkey')
    op.create_foreign_key(None, 'recordatorios_docente', 'users', ['profesor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('refresh_tokens_usuario_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_solicitudes_id'), 'solicitudes', ['id'], unique=False)
    op.drop_constraint(op.f('solicitudes_tipo_tramite_id_fkey'), 'solicitudes', type_='foreignkey')
    op.drop_constraint(op.f('solicitudes_resuelto_por_fkey'), 'solicitudes', type_='foreignkey')
    op.create_foreign_key(None, 'solicitudes', 'tipos_tramite', ['tipo_tramite_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'solicitudes', 'users', ['resuelto_por'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('suscripciones_push_user_id_fkey'), 'suscripciones_push', type_='foreignkey')
    op.create_foreign_key(None, 'suscripciones_push', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tipos_tramite_id'), 'tipos_tramite', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('users_carrera_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'carreras', ['carrera_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_carrera_id_fkey'), 'users', 'carreras', ['carrera_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_tipos_tramite_id'), table_name='tipos_tramite')
    op.drop_constraint(None, 'suscripciones_push', type_='foreignkey')
    op.create_foreign_key(op.f('suscripciones_push_user_id_fkey'), 'suscripciones_push', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'solicitudes', type_='foreignkey')
    op.drop_constraint(None, 'solicitudes', type_='foreignkey')
    op.create_foreign_key(op.f('solicitudes_resuelto_por_fkey'), 'solicitudes', 'users', ['resuelto_por'], ['id'])
    op.create_foreign_key(op.f('solicitudes_tipo_tramite_id_fkey'), 'solicitudes', 'tipos_tramite', ['tipo_tramite_id'], ['id'])
    op.drop_index(op.f('ix_solicitudes_id'), table_name='solicitudes')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_usuario_id_fkey'), 'refresh_tokens', 'users', ['usuario_id'], ['id'])
    op.drop_constraint(None, 'recordatorios_docente', type_='foreignkey')
    op.create_foreign_key(op.f('recordatorios_docente_profesor_id_fkey'), 'recordatorios_docente', 'users', ['profesor_id'], ['id'])
    op.alter_column('recordatorios_docente', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'procesos_graduacion', type_='foreignkey')
    op.create_foreign_key(op.f('procesos_graduacion_tutor_id_fkey'), 'procesos_graduacion', 'users', ['tutor_id'], ['id'])
    op.drop_constraint(None, 'postulaciones_beca', type_='foreignkey')
    op.drop_constraint(None, 'postulaciones_beca', type_='foreignkey')
    op.create_foreign_key(op.f('postulaciones_beca_beca_id_fkey'), 'postulaciones_beca', 'becas_catalogo', ['beca_id'], ['id'])
    op.create_foreign_key(op.f('postulaciones_beca_revisado_por_fkey'), 'postulaciones_beca', 'users', ['revisado_por'], ['id'])
    op.drop_constraint(None, 'pasantias', type_='foreignkey')
    op.drop_constraint(None, 'pasantias', type_='foreignkey')
    op.create_foreign_key(op.f('pasantias_empresa_id_fkey'), 'pasantias', 'empresas_receptoras', ['empresa_id'], ['id'])
    op.create_foreign_key(op.f('pasantias_tutor_academico_id_fkey'), 'pasantias', 'users', ['tutor_academico_id'], ['id'])
    op.drop_constraint(None, 'pagos', type_='foreignkey')
    op.create_foreign_key(op.f('pagos_cuota_id_fkey'), 'pagos', 'cuotas', ['cuota_id'], ['id'])
    op.drop_constraint(None, 'inscripciones', type_='foreignkey')
    op.create_foreign_key(op.f('inscripciones_alumno_id_fkey'), 'inscripciones', 'users', ['alumno_id'], ['id'])
    op.drop_constraint(None, 'informes_pasantia', type_='foreignkey')
    op.create_foreign_key(op.f('informes_pasantia_pasantia_id_fkey'), 'informes_pasantia', 'pasantias', ['pasantia_id'], ['id'])
    op.alter_column('foro_mensajes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('foro_hilos', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'examenes', type_='foreignkey')
    op.create_foreign_key(op.f('examenes_profesor_id_fkey'), 'examenes', 'users', ['profesor_id'], ['id'])
    op.drop_constraint(None, 'eventos_calendario', type_='foreignkey')
    op.create_foreign_key(op.f('eventos_calendario_creado_por_fkey'), 'eventos_calendario', 'users', ['creado_por'], ['id'])
    op.drop_constraint(None, 'equivalencias_materia', type_='foreignkey')
    op.create_foreign_key(op.f('equivalencias_materia_solicitud_id_fkey'), 'equivalencias_materia', 'solicitudes_equivalencia', ['solicitud_id'], ['id'])
    op.drop_constraint(None, 'cuotas', type_='foreignkey')
    op.drop_constraint(None, 'cuotas', type_='foreignkey')
    op.create_foreign_key(op.f('cuotas_concepto_id_fkey'), 'cuotas', 'conceptos_arancel', ['concepto_id'], ['id'])
    op.create_foreign_key(op.f('cuotas_generado_por_fkey'), 'cuotas', 'users', ['generado_por'], ['id'])
    op.drop_constraint(None, 'comprobantes', type_='foreignkey')
    op.create_foreign_key(op.f('comprobantes_pago_id_fkey'), 'comprobantes', 'pagos', ['pago_id'], ['id'])
    op.drop_constraint(None, 'becas_catalogo', type_='foreignkey')
    op.create_foreign_key(op.f('becas_catalogo_fuente_id_fkey'), 'becas_catalogo', 'fuentes_beca', ['fuente_id'], ['id'])
    op.drop_constraint(None, 'becas_activas', type_='foreignkey')
    op.drop_constraint(None, 'becas_activas', type_='foreignkey')
    op.create_foreign_key(op.f('becas_activas_beca_id_fkey'), 'becas_activas', 'becas_catalogo', ['beca_id'], ['id'])
    op.create_foreign_key(op.f('becas_activas_otorgado_por_fkey'), 'becas_activas', 'users', ['otorgado_por'], ['id'])
    op.drop_constraint(None, 'apuntes', type_='foreignkey')
    op.create_foreign_key(op.f('apuntes_user_id_fkey'), 'apuntes', 'users', ['user_id'], ['id'])
    op.alter_column('apuntes', 'fecha_subida',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('temarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('materia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semana', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bibliografia', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name=op.f('temarios_materia_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('temarios_pkey'))
    )
    op.create_index(op.f('ix_temarios_id'), 'temarios', ['id'], unique=False)
    # ### end Alembic commands ###
