"""add examenes + inscripciones_examen

Revision ID: b890f76d76ae
Revises: v0w1x2y3z4a5
Create Date: 2026-07-11 17:55:51.145665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b890f76d76ae'
down_revision: Union[str, Sequence[str], None] = 'v0w1x2y3z4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=True),
    sa.Column('hora_fin', sa.String(length=5), nullable=True),
    sa.Column('aula', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=False),
    sa.Column('cupos', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examenes_id'), 'examenes', ['id'], unique=False)
    op.create_table('inscripciones_examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('inscripto_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examen_id', 'alumno_id', name='uq_inscripcion_examen_alumno')
    )
    op.create_index(op.f('ix_inscripciones_examen_id'), 'inscripciones_examen', ['id'], unique=False)
    op.alter_column('apuntes', 'tipo_contenido',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pdf'::character varying"))
    op.alter_column('apuntes', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('apuntes', 'descargas',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('apuntes', 'visibilidad',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'publico'::character varying"))
    op.create_index(op.f('ix_auditoria_override_mora_id'), 'auditoria_override_mora', ['id'], unique=False)
    op.create_index(op.f('ix_avance_alumno_pensum_id'), 'avance_alumno_pensum', ['id'], unique=False)
    op.create_index(op.f('ix_becas_activas_id'), 'becas_activas', ['id'], unique=False)
    op.create_index(op.f('ix_becas_catalogo_id'), 'becas_catalogo', ['id'], unique=False)
    op.create_index(op.f('ix_comprobantes_id'), 'comprobantes', ['id'], unique=False)
    op.create_index(op.f('ix_conceptos_arancel_id'), 'conceptos_arancel', ['id'], unique=False)
    op.create_index(op.f('ix_correlatividades_id'), 'correlatividades', ['id'], unique=False)
    op.create_index(op.f('ix_cuotas_id'), 'cuotas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_receptoras_id'), 'empresas_receptoras', ['id'], unique=False)
    op.create_index(op.f('ix_equivalencias_materia_id'), 'equivalencias_materia', ['id'], unique=False)
    op.create_index(op.f('ix_etapas_tesis_id'), 'etapas_tesis', ['id'], unique=False)
    op.create_index(op.f('ix_examenes_suficiencia_id'), 'examenes_suficiencia', ['id'], unique=False)
    op.alter_column('foro_hilos', 'fijado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('foro_hilos', 'cerrado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_fuentes_beca_id'), 'fuentes_beca', ['id'], unique=False)
    op.create_index(op.f('ix_informes_pasantia_id'), 'informes_pasantia', ['id'], unique=False)
    op.alter_column('inscripciones', 'oferta_materia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_materias_nombre'), table_name='materias')
    op.create_index(op.f('ix_materias_nombre'), 'materias', ['nombre'], unique=False)
    op.create_index(op.f('ix_ofertas_materia_id'), 'ofertas_materia', ['id'], unique=False)
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_index(op.f('ix_pasantias_id'), 'pasantias', ['id'], unique=False)
    op.create_index(op.f('ix_pensum_materias_id'), 'pensum_materias', ['id'], unique=False)
    op.create_index(op.f('ix_postulaciones_beca_id'), 'postulaciones_beca', ['id'], unique=False)
    op.create_index(op.f('ix_procesos_graduacion_id'), 'procesos_graduacion', ['id'], unique=False)
    op.create_index(op.f('ix_recordatorios_docente_id'), 'recordatorios_docente', ['id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.create_index(op.f('ix_solicitudes_equivalencia_id'), 'solicitudes_equivalencia', ['id'], unique=False)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_verificacion_solvencia_id'), 'verificacion_solvencia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verificacion_solvencia_id'), table_name='verificacion_solvencia')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_solicitudes_equivalencia_id'), table_name='solicitudes_equivalencia')
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.drop_index(op.f('ix_recordatorios_docente_id'), table_name='recordatorios_docente')
    op.drop_index(op.f('ix_procesos_graduacion_id'), table_name='procesos_graduacion')
    op.drop_index(op.f('ix_postulaciones_beca_id'), table_name='postulaciones_beca')
    op.drop_index(op.f('ix_pensum_materias_id'), table_name='pensum_materias')
    op.drop_index(op.f('ix_pasantias_id'), table_name='pasantias')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_index(op.f('ix_ofertas_materia_id'), table_name='ofertas_materia')
    op.drop_index(op.f('ix_materias_nombre'), table_name='materias')
    op.create_index(op.f('ix_materias_nombre'), 'materias', ['nombre'], unique=True)
    op.alter_column('inscripciones', 'oferta_materia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_informes_pasantia_id'), table_name='informes_pasantia')
    op.drop_index(op.f('ix_fuentes_beca_id'), table_name='fuentes_beca')
    op.alter_column('foro_hilos', 'cerrado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('foro_hilos', 'fijado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_examenes_suficiencia_id'), table_name='examenes_suficiencia')
    op.drop_index(op.f('ix_etapas_tesis_id'), table_name='etapas_tesis')
    op.drop_index(op.f('ix_equivalencias_materia_id'), table_name='equivalencias_materia')
    op.drop_index(op.f('ix_empresas_receptoras_id'), table_name='empresas_receptoras')
    op.drop_index(op.f('ix_cuotas_id'), table_name='cuotas')
    op.drop_index(op.f('ix_correlatividades_id'), table_name='correlatividades')
    op.drop_index(op.f('ix_conceptos_arancel_id'), table_name='conceptos_arancel')
    op.drop_index(op.f('ix_comprobantes_id'), table_name='comprobantes')
    op.drop_index(op.f('ix_becas_catalogo_id'), table_name='becas_catalogo')
    op.drop_index(op.f('ix_becas_activas_id'), table_name='becas_activas')
    op.drop_index(op.f('ix_avance_alumno_pensum_id'), table_name='avance_alumno_pensum')
    op.drop_index(op.f('ix_auditoria_override_mora_id'), table_name='auditoria_override_mora')
    op.alter_column('apuntes', 'visibilidad',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'publico'::character varying"))
    op.alter_column('apuntes', 'descargas',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('apuntes', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('apuntes', 'tipo_contenido',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pdf'::character varying"))
    op.drop_index(op.f('ix_inscripciones_examen_id'), table_name='inscripciones_examen')
    op.drop_table('inscripciones_examen')
    op.drop_index(op.f('ix_examenes_id'), table_name='examenes')
    op.drop_table('examenes')
    # ### end Alembic commands ###
