"""add_created_at_to_pasantias

Revision ID: c0e2c42a4b9d
Revises: 61880be1d112
Create Date: 2026-07-22 15:25:13.699149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e2c42a4b9d'
down_revision: Union[str, Sequence[str], None] = '61880be1d112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pasantias', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pasantias', 'created_at')
    # ### end Alembic commands ###
