"""add pesos_evaluacion, migrar puntajes a escala de puntos

Revision ID: caf9713210dd
Revises: c8f8d13b8612
Create Date: 2026-07-22 19:50:34.834190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf9713210dd'
down_revision: Union[str, Sequence[str], None] = 'c8f8d13b8612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesos_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('parcial1_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('parcial2_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('practico_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('materia_id', name='uq_peso_evaluacion_materia')
    )
    op.create_index(op.f('ix_pesos_evaluacion_id'), 'pesos_evaluacion', ['id'], unique=False)
    # ### end Alembic commands ###

    # ─── Data migration: escala 0-10 → puntos (default 20/20/10/50), "final" → "final1" ───
    # Los pesos por defecto suman 100, asi promedio = puntos_obtenidos/10 sigue siendo 0-10
    # para PPA/boleta/regularidad sin tocar esos consumidores.
    op.execute("UPDATE puntajes SET tipo = 'final1' WHERE tipo = 'final'")
    op.execute("UPDATE puntajes SET valor = valor * 2 WHERE tipo IN ('parcial1', 'parcial2')")
    op.execute("UPDATE puntajes SET valor = valor * 5 WHERE tipo IN ('final1', 'final2', 'final3')")
    # practico: max 10 tanto antes (0-10) como ahora (0-10 puntos) -> sin reescalar


def downgrade() -> None:
    """Downgrade schema."""
    # Revertir escala antes de tocar el schema
    op.execute("UPDATE puntajes SET valor = valor / 2 WHERE tipo IN ('parcial1', 'parcial2')")
    op.execute("UPDATE puntajes SET valor = valor / 5 WHERE tipo IN ('final1', 'final2', 'final3')")
    op.execute("UPDATE puntajes SET tipo = 'final' WHERE tipo = 'final1'")
    op.execute("DELETE FROM puntajes WHERE tipo IN ('final2', 'final3')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pesos_evaluacion_id'), table_name='pesos_evaluacion')
    op.drop_table('pesos_evaluacion')
    # ### end Alembic commands ###
